workspace = { members = ["fraction"] }
[package]
name = "math_work2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_fraction ={ path="fraction" }